### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by CaoHoa1** [gauravsacc/MMM-GoogleAssistant#20]
pubnub subscription completed
Traceback (most recent call last):
  File "assistant.py", line 133, in <module>
    main()
  File "assistant.py", line 130, in main
    init_googleAssistant()
  File "assistant.py", line 124, in init_googleAssistant
    with Assistant(credentials) as assistant:
TypeError: __init__() missing 1 required positional argument: 'device_model_id'

**Comment by gauravsacc** [comment]
see this issue https://github.com/gauravsacc/MMM-GoogleAssistant/issues/16 here. The new SDK changes introduced this another parameter. I'm updating the assistant.py to include this change.
Please update 'magic-mirror-device-id' with your unique id.

**Comment by CaoHoa1** [comment]
ok tks

2018-01-12 11:23 GMT+07:00 Gaurav Singh <notifications@github.com>:
