### ISSUE TITLE
No module named 'PubNub'

### ISSUE THREAD

**Issue by btw1004** [gauravsacc/MMM-GoogleAssistant#53]
I'm aware this issue has been touched on already but even after following all those possible solutions I'm still left with the same error.
Traceback (most recent call last):
  File "/home/pi/assistant.py", line 31, in <module>
    from PubNub.callbacks import SubscribeCallback
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 317, in _custom_import
   module = self._original_import(*args, **kw)
ImportError: No module named 'pubnub'

Can somebody please help me, I've literally spend the past 4 days on this and I can't fix it for the life of me.

**Comment by Nairod26** [comment]
Hi. To solve your problem you need to install pubnub.
first of all activate python (for example from your home directory) : source env/bin/activate
Then : pip install pubnub
It do the job for me.... GL
Do

**Comment by Nairod26** [comment]
Another tip was useful for me, the async method seems to be depreciated in python 3.
Replace async from the assistant.py file by pn_async (three times).

**Comment by shohagrana64** [comment]
@Nairod26  it doesnt work now :(  can you please give me the new assistant.py file?

**Comment by Nairod26** [comment]
[assistant.py.tar.gz](https://github.com/gauravsacc/MMM-GoogleAssistant/files/3389666/assistant.py.tar.gz)

**Comment by shohagrana64** [comment]
@Nairod26 thank you so much. but i still get the same error..
/home/pi/env/bin/python3 -u assistant.pyTraceback (most recent call last):
  File "assistant.py", line 27, in <module>
    from google.assistant.library import Assistant
ImportError: No module named 'google.assistant.library'

can you help me with it?
NOTE: The sample code runs:
Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:Transcript of user request: "what".
INFO:root:Transcript of user request: "what is".
INFO:root:Transcript of user request: "what is the".
INFO:root:Transcript of user request: "what is the mean".
INFO:root:Transcript of user request: "what is the meaning".
INFO:root:Transcript of user request: "what  is the meaning of".
INFO:root:Transcript of user request: "what is  the meaning of lifx".
INFO:root:Transcript of user request: "what is  the meaning of life".
INFO:root:Transcript of user request: "what is the  meaning of life".
INFO:root:Transcript of user request: "what is the meaning  of life".
INFO:root:End of audio request detected.
INFO:root:Stopping recording.

**Comment by shohagrana64** [comment]
Also don't forget to delete your pubnub keys before giving the file.

**Comment by shohagrana64** [comment]
nevermind.. its working now.. 
all i did was i installed assistant in the env mode
pip3 install google-assistant-library==0.1.0

:D it works grreat now

**Comment by write2warriors** [comment]
Where do we download the assistant.py, and where do we save that to?
